### ISSUE TITLE
在pascal数据集上训练了270多个epoch，训练精度达到了97%左右，但是测试ap在0.7上才不到0.07？

### ISSUE THREAD

**Issue by zhangtao22** [unsky/RetinaNet#6]
请问这个在pascal上有人试过嘛？

**Comment by unsky** [comment]
训练过程中1gpu的参数很难调整，sgd很难收敛，我修改了训练参数，你可以试试，使用adam，训练了十几次达到了60+，在voc上的精度目前还在尝试优化。

**Comment by coldgemini** [comment]
多用几个GPU会变好吗？

**Comment by huxian0402** [comment]
我也遇到了同样的问题，在voc07上训练了50个epoch，精度达到了82%，但是精度只有Mean AP@0.7 = 0.0769。
